#!/bin/bash
set -e
cd `dirname $0`

PROJECT_ID=`gcloud config get-value project --configuration event-source`
IMAGE=gcr.io/$PROJECT_ID/default/event-gateway

# Copy to deploy as not git-ignored file
cp gcloud-configs/event-gateway-iam.json ./

gcloud builds submit \
  --tag $IMAGE
gcloud beta run deploy event-gateway \
  --image $IMAGE \
  --platform managed \
  --set-env-vars PROJECT_ID=$PROJECT_ID,KEY_FILENAME=/usr/src/app/event-gateway-iam.json \
  --region asia-northeast1

# Clean up
rm ./event-gateway-iam.json
