#!/bin/bash
set -e
cd `dirname $0`

IMAGE=gcr.io/`gcloud config get-value project --configuration event-source`/default/event-gateway

gcloud builds submit --tag $IMAGE
gcloud beta run deploy --image $IMAGE --platform managed

